// Generated by scripts/clicker-bgm.py — re-run it instead of editing by hand.
/** Seconds of seamless loop in each bgm_<key>.mp3 (the file carries 1s of pre-roll on top). */
export const BGM_LOOP_SECONDS = {
  core_chamber: 50.526326530612245,
  signal_relay: 54.857142857142854,
  phase_vault: 61.93548752834467,
  storm_spire: 48.0,
  deep_fault: 66.20689342403628,
  drone_foundry: 53.333333333333336,
  mine: 41.73913832199546,
  battle: 45.714285714285715,
} as const
