// Generated by scripts/clicker-bgm.py — re-run it instead of editing by hand.
/** Seconds of seamless loop in each bgm_<key>.mp3 (the file carries 1s of pre-roll on top). */
export const BGM_LOOP_SECONDS = {
  core_chamber: 64.0,
  signal_relay: 68.57142857142857,
  phase_vault: 73.84614512471656,
  storm_spire: 64.0,
  deep_fault: 76.8,
  drone_foundry: 66.20689342403628,
  mine: 50.526326530612245,
} as const
